project:
  type: book
  output-dir: docs

book:
  title: "EMBED2Social Workshop 2026"
  author: "EMBED2Social Imago Team"
  date: today

  page-footer:
    left: |
      EMBED2Social
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  repo-url: https://github.com/Imago-SDRUK/EMBED2Social-Workshop-2026
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - 01-Lecture_slides.qmd
    - 02-Lecture_slides.qmd

format:
  html:
    theme: cosmo
    include-in-header: |
      <script defer src="https://events.imago.ac.uk/script.js" data-website-id="1d384e7c-c043-45bd-9404-abb364ffe9e0"></script>
  pdf:
    documentclass: scrreprt

editor: visual

# Website URL for reference
url: https://imago-sdruk.github.io/EMBED2Social-Workshop-2026/
