project:
  type: website
  output-dir: ./docs
  resources:
    - "assets/*"

website:
  title: "EMBED2Social Workshop 2026"

  page-footer:
    center: |
      [Imago](https://imago.ac.uk), part of the [Smart Data Research UK](https://www.sdruk.ukri.org/) family.

  repo-url: https://github.com/Imago-SDRUK/EMBED2Social-Workshop-2026
  repo-branch: main

  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/Imago-SDRUK/EMBED2Social-Workshop-2026
    contents:
      - index.qmd
      - Materials.qmd
      - text: Imago
        href: https://imago.ac.uk

format:
  html:
    theme:
      - cosmo
      - assets/imago-theme.scss
    include-in-header:
      - text: |
          <script defer src="https://events.imago.ac.uk/script.js" data-website-id="1d384e7c-c043-45bd-9404-abb364ffe9e0"></script>

editor: visual

# Website URL for reference
url: https://imago-sdruk.github.io/EMBED2Social-Workshop-2026/
